name: locator_di
description: "A lightweight, Flutter-free dependency injection service locator."
version: 0.0.1
homepage:

resolution: workspace

environment:
  sdk: ">=3.13.0 <4.0.0"

dependencies:
  meta: ^1.19.0

dev_dependencies:
  lints: ^6.0.0
  flutter_test:
    sdk: flutter
